### ISSUE TITLE
User Story: All Products

### ISSUE THREAD

**Issue by tamariam** [tamariam/Kiddie-Corner#12]
As a **user**, I want to  **be able to see a comprehensive list of all products**  so that I can **select the ones I want to buy**

## Acceptance Criteria
- When I click the "All Products" link from the main navigation menu, I should be redirected to the All Products page.
- After reaching the All Products page, I expect to see a well-organized layout that displays all available products.
- Each product should include relevant details such as name, price, rating, stock status and description in a clear and understandable format.

## Tasks
- [x] Modify the main menu layout to include a clickable link labeled "All Products
- [x] create module for products
- [x]  create  products template.
- [x]  Design the template to accommodate product details such as name, price, description,  image, rating, stock status, 
- [x] create view to display products template on page
- [x]  Define URLs.
