### ISSUE TITLE
User Story: Product Details

### ISSUE THREAD

**Issue by tamariam** [tamariam/Kiddie-Corner#13]
As a **user**, I want to **view detailed product information** so that I can **check the details and make informed purchase decisions**.

## Acceptance Criteria
- When I click on a specific product from the product listing, I should be redirected to a detailed product page
- The detailed product page should display comprehensive information about the selected product, including its name, description, price, availability, rating, sku and any relevant images.
- If the product is out of stock or unavailable, this status should be clearly indicated on the product details page.
- There should be an option to add the product to the shopping bag, go  back to products page, or add to favorites directly from the product details page.

## Tasks
- [x] create template for product detail page.
- [x] Implement a view function  to handle requests for the product detail page.
- [x]  set up and define URLs.
- [x]  Implement backend logic to fetch detailed product data.
- [x] create buttons  for more products, add to bag and add to favorites.
