### ISSUE TITLE
User Story : Available Products 

### ISSUE THREAD

**Issue by tamariam** [tamariam/Kiddie-Corner#17]
As a **user**, I want to have ability **view only available products** so that I can **focus on browsing and purchasing items that are currently in stock.**

## Acceptance Criteria
- The products page should include a checkbox labeled "Only Available Products".
- When the "Only Available Products" checkbox is checked, only products that are currently in stock (available) should be displayed on the page
- Products that are out of stock or unavailable should be hidden or filtered out from the displayed product list.
- The checkbox state should dynamically update the displayed products without requiring a page reload.

## Tasks
- [x] Add a checkbox labeled "Only Available Products" to the products page.
- [x]  Create a function to filter the displayed products based on the availability status when the checkbox is checked or unchecked.
- [x] Integrate the front-end filtering logic with the back-end  to fetch only available products when the checkbox is checked.
