### ISSUE TITLE
User Story: Display Total Purchase Amount 

### ISSUE THREAD

**Issue by tamariam** [tamariam/Kiddie-Corner#18]
As a  **User** I want to **see the total amount of my purchases** So that I can **review the cost of my items before completing my order**.

 ## Acceptance Criteria
- On the shopping bag page, there should be a section labeled "Shopping Report" where all information about the number of items currently in the bag and the total amount to be charged is displayed.

## Tasks
- [x] Implement functionality to update item quantities and recalculate subtotals.
- [x] Write logic to calculate and display the total purchase amount based on the sum of all item subtotals in the shopping bag.
- [x] create section for shopping report in shopping bag template 
- [x]  Implement logic to retrieve item details and quantities from the database.
