### ISSUE TITLE
User Story : Contact Us

### ISSUE THREAD

**Issue by tamariam** [tamariam/Kiddie-Corner#26]
As **user **, I want to **send a message to the staff through a contact form**,
so that I can **inquire about products, orders, or other concerns without needing to make a phone call**.

## Acceptance Criteria

- The contact form template includes a button to submit the form. 
-  The user should receive a confirmation message indicating that their message has been sent successfully.
- The "Name," "Subject," "Email"" and "Message" fields should be required.
-  The "Email" field should validate that the input is in a proper email format.
## Tasks
- [x]  create models for contact form
- [x] create form for contact form
- [x] create contact form template
- [x] write function to render contact form  and display message after successfully sent message.
- [x] create button to send message
