### ISSUE TITLE
User Story:Testimonials

### ISSUE THREAD

**Issue by tamariam** [tamariam/Kiddie-Corner#31]
As a **user**, I want to **see testimonials** so that I can **read the experiences  from other customers and feel confident about making a purchase**.

## Acceptance Criteria
- Each testimonial should include an image, name, profession, and the testimonial text.
-  Testimonials should be displayed in a carousel format on the testimonials page.
-  Users should be able to navigate through testimonials using previous and next buttons.
-  Users should also be able to navigate using keyboard arrow keys.

## Tasks
- [x] create template for tesminolians page
- [x] Create model for Testimonials
- [x]  create view to pass data  to the template
- [x] Add previous and next buttons to the carousel in the template.
