### ISSUE TITLE
User Story:My Account

### ISSUE THREAD

**Issue by tamariam** [tamariam/Kiddie-Corner#32]
As a **registered user,** I want to **access and manage my order details on the My Account page**, so that I can easily **view specific order details, and update my delivery information**.

## Acceptance Criteria
- Given that I am a registered user, When I click on the user icon in the navigation bar,Then I should see a dropdown menu with an option to go to "My Account."
- Given that I am on the My Account page, When I view the list of my previous orders,Then I should see all the orders I have placed
- Given that I am on the My Account page and see my list of orders,
When I click on a specific order number, Then I should be redirected to the checkout_success page, And I should see all the details of that specific order.

## Tasks
- [x] add  profile link to navigation
- [x] create  template for profile page
- [x]  Implement a view function to fetch the logged-in user's profile and order data from the database.
- [x]  Pass the fetched data to the profile page template for rendering.
