### ISSUE TITLE
User Story:Update Delivery Information

### ISSUE THREAD

**Issue by tamariam** [tamariam/Kiddie-Corner#33]
As a **registered user,** I want to **update my delivery information** on the My Account page,
so that **my orders are delivered to the correct address**.

## Acceptance Criteria
- Given that I am on the My Account page,
When I click the "Update Information" button,
Then I should see a form to update my delivery details.
- Given that I have entered my new delivery information,
When I submit the form,
Then the system should update my delivery information in the database.
- Given that I have successfully updated my delivery information,
When the update is completed,
Then I should see a success message confirming that my delivery information has been updated.

## Tasks

- [x] create userprofile model
- [x] Create an HTML form for updating delivery information.
- [x]  Add an "Update Information" button to the My Account page.
- [x] Implement a view function to handle the display of the update form.
- [x] Implement a view function to process the form submission and update the delivery information in the database.
- [x] add success message to the view to display a success message after the delivery information has been successfully updated.
