### ISSUE TITLE
User Story:Edit Product

### ISSUE THREAD

**Issue by tamariam** [tamariam/Kiddie-Corner#35]
as a **staff member** i can  **edit products** So that I can **update product details** as needed.

## Acceptance Criteria
- For each product displayed on the products or product details page, there should be an "Edit" option.
- Clicking the "Edit" option for a product should redirect the staff member to the Edit Product page.
- The Edit Product page should display the existing product details in an editable form.
- Changes made to the product details should be reflected in the product database upon submission.

## Tasks
- [x] Design the layout and fields for the Edit Product form on the Edit Product page.(only for staff members
- [x] Modify the templates to display an "Edit" option for each product listed on the Product and product detail page and 
Ensure the option is only visible to staff members.
- [x]  Develop backend logic to handle redirection to the Edit Product page when the "Edit" option is clicked.
- [x] Develop backend logic to handle submission of the Edit Product form.
