### ISSUE TITLE
User Story:Delete Product

### ISSUE THREAD

**Issue by tamariam** [tamariam/Kiddie-Corner#36]
as a **staff member** i want **to delete product**  so that I can **remove outdated or unnecessary items from the inventory**.

## Acceptance Criteria
- For each product displayed on the Product/product detail page, there should be a "Delete" option(only for staff members).
-  After clicking delete the product should be removed from the inventory database.
- Upon successful deletion, a confirmation message should be displayed.

## Tasks
- [x]  Modify the products/product details page to display a "Delete" option for each product listed(only for staff members).
- [x] Implement backend logic to handle the deletation.
- [x] Implement frontend logic to display a confirmation message after successful deletion of a product.
