### ISSUE TITLE
User Story: Add Testimonials

### ISSUE THREAD

**Issue by tamariam** [tamariam/Kiddie-Corner#37]
As a **staff member**, I want to **add a testimonial from the product management page** so that I can **showcase positive feedback about our products to our users**.

## Acceptance Criteria
-  On product management page there should be  section for testimonials.
-  testimonials section  should display a form with fields for product name, description, price, category, and other relevant details.
- The form should include two buttons: "Add Testimonial" and "Cancel".

## Tasks
- [ ]  Modify product management page to have section for testimonials
- [ ]  Develop the backend view and form.py to render the testimonials form
- [ ]  add 'cancel' and 'add_testimonial' buttons to testimonials section
