### ISSUE TITLE
User Story: Deployment

### ISSUE THREAD

**Issue by tamariam** [tamariam/Kiddie-Corner#4]
As a **developer** I want to **deploy the website on Heroku** so that i can  **test its functionality in a live environment and make the completed site accessible to the public**.

## Tasks
- [x] Create a new Heroku app.
- [x] connect to database
- [x] Add config vars in Heroku settings
- [x] Add Heroku as an allowed host in Django settings
- [x] Create Procfile
- [x]  Connect the Heroku app to my GitHub repository.
- [x] Deploy the site
- [x] create runtime.txt file
