### ISSUE TITLE
User Story: Site login and logout

### ISSUE THREAD

**Issue by tamariam** [tamariam/Kiddie-Corner#7]
as a **user** i can **login**  to ** use all features of site**

## Acceptance Criteria

- As a registered user not currently signed in, upon visiting the login page and providing my credentials, I should be successfully logged into my account.

- As a logged-in user, when I choose to logout and confirm the request, the system should perform a successful logout, ending my current session.

## Tasks
- [x] Create login and logout functionality
- [x] create login and logout buttons.
- [x] create appropriate forms for login and logout
